import pygame

# Dimensiones de la pantalla de Pygame
ANCHO_PANTALLA = 800
ALTO_PANTALLA = 650

# Colores (formato RGB) 
BLANCO = (219, 31, 0, 86)
NEGRO = (0, 0, 0, 86)
ROJO = (92, 52, 46, 86)
VERDE = (92, 46, 79, 86)
AZUL = (44, 217, 219, 86)
GRIS_CLARO = (89, 92, 77, 86)

# ============================
# --- VARIABLES "ESTABLES" ---
# ============================

# Drones Físicos
RADIO_DRONE = 10.0
MASA_DRONE = 2.0 

# Fuerzas Internas
DISTANCIA_SEPARACION_MIN = RADIO_DRONE * 2.5  # 25.0
EPSILON_FUERZA = 1e-4

# Obstáculos Físicos
MIN_TAMANO_OBSTACULO = 10.0
MAX_TAMANO_OBSTACULO = 20.0
RADIO_OBSTACULO = MAX_TAMANO_OBSTACULO / 2.0
DISTANCIA_REACCION_OBSTACULO = RADIO_DRONE + MAX_TAMANO_OBSTACULO

# Obstáculos Dinámicos
TIEMPO_VIDA_OBSTACULO_MIN = 10.0
TIEMPO_VIDA_OBSTACULO_MAX = 20.0
TIEMPO_RESPAWN_OBSTACULO_MIN = 5.0
TIEMPO_RESPAWN_OBSTACULO_MAX = 15.0
MAX_OBSTACULOS_SIMULTANEOS = 5 

# Exploración Fija
RADIO_BUSQUEDA_FRONTERA_DRONE = 400.0

# Colisiones Fijas
PROBABILIDAD_FALLO_POR_COLISION_OBSTACULO = 0.9
PROBABILIDAD_FALLO_POR_COLISION_DRON = 0.9
DISTANCIA_COLISION_DRON_DRON = 2
DISTANCIA_COLISION_DRON_OBSTACULO = 2

# Bordes Fijos
K_BORDE_REPULSION = 2000.0
DISTANCIA_REACCION_BORDE = RADIO_DRONE * 2.5  

# CBF Fijos
CBF_D_MIN_DRON_OBSTACULO = RADIO_DRONE + RADIO_OBSTACULO
CBF_GAMMA = 1  

# RNG Fijos (Mantén tus semillas para reproducibilidad)
GCL_SEED_ENTORNO = 946548256
GCL_MULTIPLIER_A = 1664525
GCL_INCREMENT_C = 1013904223
GCL_MODULUS_M = 2**32
MIDDLE_SQUARE_SEED_DRONES = 6453215
N_DIGITS_MIDDLE_SQUARE = 8
GCL_SEED_OBSTACULOS_DYN = 7485316
GCL_MULTIPLIER_A_OBS = 1103515245
GCL_INCREMENT_C_OBS = 12345
GCL_MODULUS_M_OBS = 2**31

# Otros Fijos
COLOR_CELDA_NO_CUBIERTA = (45, 134, 64, 53)
COLOR_CELDA_CUBIERTA = (29, 177, 61, 69)
COLOR_DRON_INACTIVO = (100, 100, 100)
TECLA_PAUSA_REANUDAR = pygame.K_SPACE
TECLA_RESETEAR = pygame.K_r
TECLA_ANADIR_DRON = pygame.K_a
TECLA_QUITAR_DRON = pygame.K_q
RNG_TEST_NUM_SAMPLES = 10000
RNG_TEST_NUM_BINS_CHI2 = 10
TECLA_EJECUTAR_RNG_TESTS = pygame.K_t
VERBOSE = True

# ==============================================================================
# --- VARIABLES "EDITABLES" ---
# ==============================================================================

# Simulación General
NUM_DRONES_INICIAL = 15   
FPS = 60.0 
DELTA_T = 1 / FPS

# Comportamiento del Enjambre
K_COHESION = 1.0           
K_SEPARATION = 1000.0    
K_ALIGNMENT = 5           
K_FRONTIER_ATTRACTION = 50 
SENSOR_RANGE_DRONE = 250.0
MAX_VELOCIDAD = 500       
MAX_FUERZA = 5000.0

# Obstáculos
NUM_OBSTACULOS = 5         
K_OBSTACLE_REPULSION = 1500.0 
OBSTACULOS_DINAMICOS_PORCENTAJE = 0.1 
GENERAR_NUEVOS_OBSTACULOS_INTERVALO = 30.0 

# Control Barrier Functions (CBF)
CBF_ACTIVADO = True         
CBF_D_MIN_DRON_DRON = 25.0
CBF_FACTOR_CORRECCION_VELOCIDAD = 0.2

# Cobertura
TAMANO_CELDA_COBERTURA = 50